# default
spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  batch:
    job:
      name: ${job.name:NONE}
      enabled: false          # 프로젝트가 실행될때 파라미터가 존재하더라도 Job 이 실행되지 않는다.
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:4447/spring_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true

---

spring:
   config:
     activate:
       on-profile: test
   jpa:
    database: h2